[package]
name = "stream"
version = "0.1.0"
authors = ["Kazuki Matsuo <kazuki.matsuo.728@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.20.0"

[[bin]]
name = "cat"
path = "src/cat/main.rs"